### ISSUE TITLE
MC1.13 v1.0.0b20180806052157-beta client crash on startup

### ISSUE THREAD

**Issue by kreezxil** [UpcraftLP/Rift-Wastelands#1]
https://paste.ee/p/bYeS7

**Comment by UpcraftLP** [comment]
testing shows that this is a compatibility issue with RandomConfigs

**Comment by UpcraftLP** [comment]
Yup, totally not on my end, the game will crash anyways with wastelands disabled, but will run fine with RandomConfigs disabled.
EDIT: posted an issue on their tracker: https://github.com/TheRandomLabs/RandomConfigs/issues/3
